### ISSUE TITLE
failing requests from the app due Redis SSL issue

### ISSUE THREAD

**Issue by gassc** [3rww/data-api#36]
All requests to the async endpoint from the web app are failing due to a Redis connection issue.

This may be a result of the Heroku-imposed upgrade from Redis 5.x to 7 ~~on June 16~~ today.

Logs:

```
2023-06-27T00:04:22.000000+00:00 app[redis-sinuous-87740]: Error accepting a client connection: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
2023-06-27T00:04:22.080126+00:00 app[web.1]: 2023-06-26 20:04:22 [10] [ERROR] pathname=/app/.heroku/python/lib/python3.10/site-packages/django/utils/log.py lineno=241 funcname=log_response Internal Server Error: /admin/django_rq/queue/
2023-06-27T00:04:22.080148+00:00 app[web.1]: Traceback (most recent call last):
2023-06-27T00:04:22.080148+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 598, in connect
2023-06-27T00:04:22.080148+00:00 app[web.1]: sock = self.retry.call_with_retry(
2023-06-27T00:04:22.080149+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
2023-06-27T00:04:22.080149+00:00 app[web.1]: return do()
2023-06-27T00:04:22.080149+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 599, in <lambda>
2023-06-27T00:04:22.080150+00:00 app[web.1]: lambda: self._connect(), lambda error: self.disconnect(error)
2023-06-27T00:04:22.080150+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 998, in _connect
2023-06-27T00:04:22.080150+00:00 app[web.1]: sslsock = context.wrap_socket(sock, server_hostname=self.host)
2023-06-27T00:04:22.080150+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/ssl.py", line 513, in wrap_socket
2023-06-27T00:04:22.080151+00:00 app[web.1]: return self.sslsocket_class._create(
2023-06-27T00:04:22.080151+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/ssl.py", line 1071, in _create
2023-06-27T00:04:22.080151+00:00 app[web.1]: self.do_handshake()
2023-06-27T00:04:22.080152+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/ssl.py", line 1342, in do_handshake
2023-06-27T00:04:22.080152+00:00 app[web.1]: self._sslobj.do_handshake()
2023-06-27T00:04:22.080154+00:00 app[web.1]: ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
```

**Comment by gassc** [comment]
Fixed with ebc2869
